### ISSUE TITLE
Evaluating CacheControl

### ISSUE THREAD

**Issue by davidbgk** [regardscitoyens/lawfactory_utils#1]
Hello,

I had the same caching issue while dealing with law related URLs and I stumbled upon [CacheControl](http://cachecontrol.readthedocs.io/en/latest/) to use on top of requests. Might be worth considering.

**Comment by mdamien** [comment]
Yes, I looked into using it but couldn't get it to work. Also I aim for the cache store to be transparent, like being able to search the cached pages to debug them for example. With the `FileCache`, the data is passed through pickle.

But actually I may use the same approach since I would like to cache ZIP files for example.

It may interrest you: Before we were using `requests_cache`, https://github.com/reclosedev/requests-cache, and it worked very well.

Thanks for the suggestion anyway ! I mark it as solved since it has been evaluated.
